[[main]]
  name = "About"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Blog"
  weight = 2
  pageRef = "blog"

[[main]]
  name = "Projects"
  weight = 3
  pageRef = "projects"

[[main]]
  name = "Resume"
  weight = 4
  pageRef = "resume"

[[main]]
  name = ""
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/bryskiewiczr"
  target = "_blank"
  weight = 5

[[main]]
  name = ""
  identifier = "github"
  pre = "github"
  url = "https://www.github.com/bryskiewiczr"
  target = "_blank"
  weight = 6